#!/usr/bin/env bash

: "${PRODUCTIVE_K3S_SOURCE_DEFAULT:=remote}"
: "${PRODUCTIVE_K3S_CORE_VERSION_DEFAULT:=0.9.4}"
: "${PRODUCTIVE_K3S_GITHUB_OWNER_DEFAULT:=productive-k3s}"
: "${PRODUCTIVE_K3S_CORE_REPO_NAME_DEFAULT:=productive-k3s-core}"
: "${PRODUCTIVE_K3S_ADDONS_REPO_NAME_DEFAULT:=productive-k3s-addons}"
: "${PRODUCTIVE_K3S_PROFILES_REPO_NAME_DEFAULT:=productive-k3s-profiles}"
: "${PRODUCTIVE_K3S_RELEASE_REPO_DEFAULT:=${PRODUCTIVE_K3S_GITHUB_OWNER_DEFAULT}/${PRODUCTIVE_K3S_CORE_REPO_NAME_DEFAULT}}"
: "${PRODUCTIVE_K3S_CORE_GIT_REMOTE_URL_DEFAULT:=https://github.com/${PRODUCTIVE_K3S_RELEASE_REPO_DEFAULT}.git}"
: "${PRODUCTIVE_K3S_ADDONS_GIT_REMOTE_URL_DEFAULT:=https://github.com/${PRODUCTIVE_K3S_GITHUB_OWNER_DEFAULT}/${PRODUCTIVE_K3S_ADDONS_REPO_NAME_DEFAULT}.git}"
: "${PRODUCTIVE_K3S_PROFILES_GIT_REMOTE_URL_DEFAULT:=https://github.com/${PRODUCTIVE_K3S_GITHUB_OWNER_DEFAULT}/${PRODUCTIVE_K3S_PROFILES_REPO_NAME_DEFAULT}.git}"
